### ISSUE TITLE
adding automated unit and integration testing

### ISSUE THREAD

**Issue by dravog7** [iCodeDevs/EXecutioner#3]
How to do unit tests and integration tests?

Using Travis CI, unit tests and integration tests are possible but without using firejail since firejail will not work within docker.

**Comment by akhilmhdh** [comment]
Jenkins would be a good option then.

**Comment by dravog7** [comment]
Jenkins require a server and other setup. I rather find a solution that wont cost that much. though for full integration testing jenkins is required.

For now, I will add travis for unit testing.

**Comment by dravog7** [comment]
## Correction

Travis uses VM instances for testing, hence firejail and other sandboxes will work inside.
(Even docker can be made inside)
